# Introduction

_Needs to clearly outline WHY we want to predict hot water_

```{r loadFiles, include=FALSE}
dFile <- "~/HWCanalysis/Masters/data/"   # Data folder
pFile <- "/home/parra358/HWCanalysis/Masters/plots/"  # Plots folder (laTeX did not like '~' notation)
```


## Demand side management

Total electricity demand varies throughout time, with daily demand patterns in New Zealand generally exhibiting two peaks, one in the morning and one in the evening[@TranspowerNZ2015]. _Distinguish between local network and national peaks, as well as daily peaks from extreme events and seasonal peaks?_ Electricity supply must match this fluctuating demand, require underutilised generation and transmission infrustructure to be available on demand, a costly and inefficient situation[@Strbac2008]. This is likely to be exacerbated by the predicted increase of renewable energy in the grid, as renewable energy generation is often reliant on weather conditions, and consequently can not easily be shifted to meet demand[@Lund2015].
_Expand on this - why peaks matter, costs, etc, with references_
Demand side management is the process of adjusting demand to meet supply, and may play a vital role in the transition to a low-carbon electricity grid. Many electricity using devices can have their use times shifted on a daily scale with limited impact to the end user (a property referred to as "flexibility"). Devices such as washing machines and dishwashers exhibit this property, as does many thermostatically controlled appliances such as heat pumps and electric water heaters, and, rising in prominence, battery storage systems in the form of electric cars and bicycles.

## Why predict hot water electricity demand

In New Zealand, residential electricity usage contributes around half of peak demand[@ElectricityCommission2007] and residential hot water use is around 30% of residential energy used[@Pollard2002]. The tendency of people showering or bathing either before leaving the house or in the evenings means that weekday residential hot water usage often occurs during network peaks in demand. A study by the Household Energy End Use Project (HEEP) showed that hot water usage makes up to 36% of residential peak demand [@Pollard2002] and data from the GREEN Grid project suggesting it may be up to to 50%[@Jack2018]. 
In New Zealand, electric hot water cylinders (HWCs) are very common, with 91% of households having electricity as an energy source for water heating[@Pollard2002]. The ability of the HWC to store and retain up to 10kWh of energy in the form of heat renders them perfect candidates for control, and could be considered one of the most “flexible” appliances in New Zealand households[@Stephenson2017]. 

## Literature review

There is a large and active body of research that explores different methods of controlling demand-flexible appliances under various demand side management objectives. 

_The following simply lists articles. I need to instead catagorise and order the literature. Be careful not to use difficult terms or concepts without first introducing them._

_Key things to aim for in the lit review: (i) Demonstrating that I know the literature, and (ii) Identifying the gap I intend to fill with this research._

Ramchurn, Vytelingum, Rogers and Jennings, (2011) model households with generic storage capacity under a homeostatic control mechanism which uses linear optimisation to minimise consumption of high-carbon electricity by shifting electricity use over daily timescales in order to match predicted renewable energy availability. Reduction in residential carbon emissions of up to 25% were demonstrated, as were consumer savings of up to 14.5% under a carbon-based pricing mechanism. 

Mohsinian-Rad, Wong, Jatskevitch, Schober and Leon-Garcia (2010) modelled demand-side management of various residential appliances to minimise both cost of electricity to the consumer, and peak-to-average ratio of total load in the electricity grid. Real-time pricing signals were used as inputs in a game theoretical algorithm that optimised energy scheduling of flexible appliances for individual household cost minimisation. It was demonstrated that the Nash equilibrium obtained by these automatic energy schedulers was also the optimal solution for the electricity grid as a whole.

Cui, Wang, Wang and Zhang (2016) also used real-time pricing signals to schedule flexible appliances in a cooperative game that attempts to minimise consumer costs. Their control method used an autoregressive integrated moving average model to forecast electricity prices. These were then used as an input, along with modelled appliance demands, to an optimisation program which scheduled appliances such that their forecasted demand was fully satisfied at minimal cost. Under the profit-sharing assumptions used, residential electricity bills were shown to be reduced by about 4% while retailer's relative costs were reduced by 7.56%.

Yu, Jia, Murphy-Hoye, Pratt and Tong (2013) modelled demand-side management of various residential appliances, with emphasis on a thermal model of the household HVAC system. Instead of optimising a cost function under end-use satisfaction related constraints, their research focuses on maximising consumer satisfaction under a budget constraint. The controllers utilised model-predictive control with indoor and outdoor temperatures, insolation, weather reports, and prior electricity consumption as inputs for a mixed-integer stochastic optimisation problem, which schedules household appliances in an on/off manner.

O'Shaghnessy, Cutler, Ardani and Margolis (2018) used the U.S. National Renewable Energy Laboratory's Renewable Energy Optimisation (REOpt) and Building Energy Optimisation (BEOpt) models to mimimise the lifecycle cost of energy for a household through optimal configuration of PV, battery storage, smart domestic water heater, and smart AC unit. The household thermal storage devices (electric water heater, AC unit) were controlled through adjustment of the thermostat set-points through the day to take advantage of the day-time PV output. It was found that under current pricing, load-shifting through the use of smart AC units and smart domestic water heaters is a more cost effective method of increasing self-consumption of solar PV than the installation of batteries.

Other research focused solely on demand response of electric water heaters, usually employing more sophisticated thermal models which allow for greater understanding of potential impacts on service. Thermal models of hot water cylinders can span in complexity from extremely simplified one-dimensional temperature gradients, to highly complex computation fluid dynamic models using the Navier–Stokes equations. When modelling for the purpose of demand response research a suitable balance between these two extremes must be met that both accurately predicts the effect of "running out" of hot water, while being computationally inexpensive enough to run over long time periods and through optimisation iterations.

Some researchers (cite Sepulveda et al, (2010) and Kapsalis et al (2018)) opt for a single, fully mixed body of water as their thermal model. This model has the advantage of being computationally inexpensive, but is limited in its accuracy in predicting impacts on service, especially for vertical cylinders, due to its inability to capture the stratification of low-density hot water and higher-density cool water that occurs. Sepulveda, Paull, Morsi, Li, Diduch and Chang (2010) utilised this model to investigate the potential of heterogeneous control of hot water cylinders using a binary particle swarm optimisation algorithm for the purpose of reducing grid peaks. Their direct load control modelling suggested an average reduction in peak-time electricity use of between 500W-750W per household.

Kapsalis, Safouri and Hadellis (2018) also used a fully-mixed model in a multiobjective optimisation problem that considers individual user preferences as well as a hot water consumption pattern and day-ahead electricity prices to both reduce costs under a real-time pricing plan while maintaining service, with the emphasis on cost or comfort set by individual households. An heuristic optimisation algorithm with low computational complexity was utilised to operate the controller, enabling implementation by a low-cost embedded controller and relay fitted to the heating elements of conventional water heaters. 

One step beyond the single-volume well mixed thermal model in both physical accuracy and computational expense is the two-volume stratified model. This allows greater accuracy in modelling effects on service, while still remaining computationally inexpensive enough to utilise for most demand-side management modelling purposes. Kondoh, Lu, and Hammerstrom (2011) used a two-volume, vertically stratified model of a hot water cylinder with both top and bottom elements and thermostats. Usage patterns were based on hot water demand data and was simulated as discrete 2.0kWh events. The lower thermostat was controlled for varying numbers of water heaters simultaneously for the purpose of providing grid-beneficial services. It was estimated that to provide a 2-MW regulation service for 24 hours a day, it was necessary to be able to control around 33,000 water heaters.

Roux, Apperly and Booysen (2018) also use a two-volume model for their heuristic demand response solution that considers individual consumption patterns as well as hot water temperatures and physical cylinder metadata in order to reduce grid peaks as well as reduce overall energy consumption through heating water "as needed". The results showed that their proposed mechanism outperformed measured results from field units, as well as conventional "ripple controlled" units, without sacrificing user comfort.

Some research combines the computational efficiency of the single-volume well-mixed model with the physical fidelity of a multi-volume model by utilising both models for different aspects of the simulation/optimisation/control process. The control algorithm utilised by Kepplinger, Huber and Petrasch (2014) uses a single-volume well-mixed model in order to construct a cost-optimised binary switch function under real-time electricity prices using the hot water demand predicted using a kth nearest neighbour data mining algorithm. This optimised binary switch function is input along with the electrical power used by the physical hot water cylinder into a multi-volume thermal model that is used to estimate future temperatures inside the physical cylinder. These predictive temperatures are returned to the original optimisation algorithm to check that they are between the minimum and maximum temperature constraints.  

A common theme within the literature regarding the utilision of hot water cylinders for the purpose of demand side management is the necessity of accurately forecasting hot water demand. An accurate demand forecast allows for more efficient energy storage and demand response capibilites, and may lessen any negative effects (running out of hot water) to the end user.

Gelažanskas and Gamage[@Gelazanskas2015] explore a number of statistical forecasting methods to predict domestic hot water electricity use including exponential smoothing, seasonal autoregressive moving average, and a combination of them. These models were all found to outperform benchmark models such as mean, naive, and seasonal naive, with seasonal decomposition being the most important technique for forecast accuracy. _Need to expand upon how the models are developed, (based on historical data etc)._

_Include more forecast-specific papers._

_Make sure introduction has provided sufficient information that the reader will understand the research aims in next subsection._

## Aims

This project analyses and models the GREEN Grid data in order to determine forecastability of residential hot water electricity use from smart meters with seperately metered hot water, as is commonly encountered in New Zealand. This would assist in controlling hot water electricity for demand response by reducing negative effects on service. In addition, it may provide the means for hot water cylinders to participate in half-hour ahead demand response markets by providing the ability to bid an estimated capacity for load-shedding according to forecasted demand. It is an explanatory analysis and examines a number of different forecasting methods, which are compared to one another in the conclusion.