# Modelling 1 minute data {#one-min}

```{r include_packages_2, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis and also two functions
# used for labeling and referencing
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(dplyr))
    install.packages("dplyr", repos = "http://cran.rstudio.com")
if(!require(ggplot2))
    install.packages("ggplot2", repos = "http://cran.rstudio.com")
if(!require(ggplot2))
    install.packages("bookdown", repos = "http://cran.rstudio.com")
if(!require(thesisdown)){
  library(devtools)
  devtools::install_github("ismayc/thesisdown")
  }
library(thesisdown)
```


The element within a typical hot water cylinder works is controlled thermostatically by an "on-off" (otherwise known as "bang-bang") controller. This type of controller turns the element fully "on" when the water temperature drops below a certain temperature, and then fully off again once the water reaches another (slightly higher) temperature. _include diagram?_
On small timescales, the element may then be considered a binary process, impacting our choice of forecasting model. Forecasting a binary output requires more sophisticated models than forecasting a "continous" output. 

_Provide appropriate equations_
<!--
Despite the reasonable forecasting accuracy of the vector autoregression method above, the model diverges from physical reality in two crucial ways. First, the model is fitted using ordinary least squares, with no regard for maintaining the forcasted demand to be greater than zero.

In addition, vector autoregression assumes continuity of the process. While the half-hour data (being actually 30 minute averages of 1 minute data) appears roughly continuous, the 1 minute data shows the element is essentially a discrete process, with the element either being fully on or fully off.
-->

## Logistic Autoregression

Logistic Autoregression takes the autoregression model from Chapter \@ref(half-hour) and.....

## Generalised Additive Models with binary response variables

