# Literature review {#lit-rev}

This chapter provides an overview of the literature relevant to this thesis.
While this is not strictly smart control research, the aims of this thesis are best understood by considering them through the framework of smart control.
As such, this chapter begins by noting key literature relating to smart control off appliances, and any relevant findings.
Next, literature relating to electricity demand forecasting is presented. This section begins by briefly reiterating how forecasting models are constructed, and then lists a selection of models used in electricity demand forecasting. It then notes other work whereby models were compared with one another, and the results of these comparisons.
Following this is key literature regarding domestic hot water simulations. This section describes a selection of physical hot water models used in research simulations, and explains the relevance demand forecasting models may have on these.
Finally, an explanation is given as to where the research in this thesis fits in relation to existing literature.
One piece of existing research in particular, that of [@Gelazanskas2015], inspired much of the research in this thesis. A number of its methodologies were replicated, and its key findings were built upon in this work. As such, [@Gelazanskas2015] is examined in some detail in this section, with differences between it and this work made clear.

## Smart control

Smart control research generally involve estimating the benefits associated with scheduling or otherwise adjusting the operation of suitable appliances. This is generally done at key times in order to meet a number of objectives, such as:

* reducing grid peaks[@Roux2018; @Sepulveda2010, @Kepplinger2015]
* providing grid-beneficial (instantaneous response) services[@Kondoh2011]
* minimising costs under time-varying electricity prices[@Kepplinger2015; @Mohsenian-Rad2010; @OShaughnessy2018; @Sepulveda2010; @Cui2016; @Kapsalis2018]
* utilising low-carbon electricity[@Ramchurn2012; @Passenberg2016]
* maintaining consumer comfort under a budget constraint[@Yu2013]

Insulated hot water cylinders show high flexibility, and as such are good candidates for smart control, but similar objectives can be obtained with other thermal devices such as heating and air conditioning systems[@OShaughnessy2018; @Yu2013], as well as other devices such as electric vehicles and clothes washing machines/dryers[@Cui2016; @Mohsenian-Rad2010].

In order to effectively schedule appliances under smart control, reasonable estimates must be made as to when they are required to be utilised. An electric vehicle, for example, must be sufficiently charged before the next drive, clothes must be washed and dry in time for their next use, and a hot water cylinder must be sufficiently hot before the next shower. Accurate predictions of these 'next' usage events provide a smart control system the ability to fine tune their optimisation algorithms to take full advantage of the demand flexibility without negatively impacting the end user.
As such, demand forecasting in some form is common in smart control literature[@Cui2016; @Roux2018; @Arghira2012; @Kepplinger2015; @Ramchurn2012; @Sepulveda2010; @Yu2013; @Kapsalis2018; @Passenberg2016].

## Electricity demand forecasting
<!--
Many hot water electricity demand forecasting techniques use similar methods to the simulated hot water demand component of the physical models mentioned at the beginning of this section.
The key difference is in their purpose. Rather than being run in order to simulate flow events for a physical model, they are projected into the future to obtain forecasts of demand.
When used in this manner, there is no need to be replicating physical characteristics of the hot water cylinder, thus these models focus only on understanding mathematical relationships within existing demand data. 
-->
Electricity demand models are constructed using existing electricity demand data, and, in some cases, other relevant data sources that span the same period of time. The models are 'fitted' to the existing dataset such that they best replicate the existing demand data under certain constraints. Once this is completed, these models may then be projected forward in time to where no electricity demand data exists in order to provide forecasts.

Electricity demand forecasting is a large and active research area. 
While much research is conducted relating to predicting grid-level[@DeFelice2013; @Jain2009], substation level[@Goude2014], or building level[@Popescu2016; @Gajowniczek2014; @Ahmad2014; @McLoughlin2013] demand, some has been done on predicting the demand of individual household appliances [@Arghira2012], including that of hot water cylinders[@Lomet2015; @Aki2016; @Denis2019].

There is currently no consensus on the 'optimal' method for forecasting electricity demand.
Conventional techniques are commonly used, either some form of time series analysis such as ARIMA[@Lomet2015; @Arghira2012; @Popescu2016, @Denis2019], regression[@Wei2015; @McLoughlin2015; @Kaytez2015; @Dervilis2018; @Massana2015], or combination of the two[@DeFelice2013].

There are also a number of AI methods used in electricity demand forecasting. 
These include:

* ANNs[@Dervilis2018; @Chitsaz2015]
* SVMs[@Aki2016; @Jain2009; @Zhang2016]
* ensemble bagging trees[@Wang2018]
* particle swarm optimisation[@Sepulveda2010]
* reinforcement learning[@Ruelens2018]
* cluster analysis[@McLoughlin2015]
* dynamic Gaussian processes[@Dervilis2018]

ANNS and SVMs are by far the most common AI methods used for electricity demand forecasting[@Ahmad2014; @MatDaut2017; @Tardioli2015; @Amasyali2018].
Consequently, these are the methods that were explored in this research. 

While much of this research considers only one forecasting model, some research has been done that compares a selection of electricity demand forecasting models with one another.
Research comparing AI methods showed SVMs tend to outperform ANNs in accuracy[@Ahmad2014] while having reasonable computational efficiency[@Ahmad2014], whereas ANNs in particular were noted as being computationally expensive[@Dervilis2018].
While a comparison between AI methods in [@Gajowniczek2014] showed a that an ANN provides slightly more accurate forecasts when predicting a full day ahead, the SVM was most accurate when predicting the next hour. 
Some comparative research considers both AI and conventional methods[@Dervilis2018; @Kaytez2015; @Massana2015]. 
SVMs were compared against ANNs and linear regression in [@Kaytez2015; @Massana2015], and found to be the most accurate model.
SVMs were not considered in [@Dervilis2018], which instead found an AI forecasting method called dynamic Gaussian processes to be by far the most accurate when predicting grid-level electricity load.
Dynamic Gaussian processes however were noted in [@McLoughlin2013] as being unsuitable for building level demand forecasting, and thus, we may assume, also for appliance level forecasting.
A comprehensive review of data-driven building energy consumption prediction studies[@Amasyali2018] shows SVMs consistantly outperforming ANNs in accuracy for demand forecasting, which is confirmed by another review in [@MatDaut2017]. 
Comparative research in [@Gelazanskas2015] considers a number of time series analysis methods for forecasting volumetric residential hot water demand, with ARIMA models featuring as highly regarded for this purpose.

Some demand forecasting models, particularly those using conventional forecasting methods, are reasonably easy to interpret. Once they have been fitted to the data, their parameters can be extracted to provide statistical insights into the behaviour behind the data.
This is valuable for building 'physical' domestic hot water computer models, as their parameters can be used to construct more accurate simulations of hot water demand.

## Domestic hot water modelling 

Domestic hot water modelling refers to the process of building computer models that represent a residential hot water cylinder and its operation.
In the wider context of computer modelling, these are referred to as 'physical' models.
While all models are less accurate than the systems they replicate, analyses that utilise computer models have a number of crucial benefits over real-world alternatives.
Firstly, a well-constructed computer model provides the ability to make an analysis regarding alterations to the physical system that may be difficult or expensive to carry out in reality. 
Secondly, computer models provide the ability to ‘speed up’ the passing of time, and to be run ‘into the future’, two features currently unavailable when conducting real-world analyses. 
Hot water cylinder models may be utilised for a number of applications.
Some represent the physical system, with all its temperature gradients and heat and fluid flows, to a high degree of accuracy. These are suited for analyses as to the effects of making physical changes to the system, such as adjusting the position of the outlet[@Kong2016; @Yaici2013] or cylinder dimensions [@Yaici2013]. However, a high degree of physical accuracy comes with high computational cost.
The more physically simplistic models are more suitable for analyses that span over long periods of time, such as in simulations of smart control scenarios.

Generally speaking, a hot water cylinder model will consist of both a mathematical description of the physical system, and a mathematical or statistical description of the flow of hot water out of the tank, that is, hot water demand. 
A mathematical representation of the physical cylinder must, at a minimum, take into consideration the internal temperature effects of inflows of cold and outflows of hot water, heat input into the cylinder from the element, and heat loss from the walls of the cylinder.
Water temperature(s) within the cylinder are important, both for heat flow calculations, and for determining if and when the cylinder has run out of hot water.
In a cylinder of warm water at equilibrium a temperature difference between the top and bottom of the cylinder naturally arises. This can be described in terms of three distinct volumes of water. At the bottom of the cylinder, there is a volume of cooler water, with only a slight change in temperature from the bottom to the top of it. At the top, a volume of warmer water, again with only a slight vertical temperature gradient.
These are separated by a volume of water known as the thermocline, whereby a rapid change in temperature occurs between its top and bottom[@JackDew2018].
Some models choose to simplify this heat distribution within the tank, considering it instead to be one well-mixed, single temperature volume of water[@Heleno2015; @Parra2016; @Roux2017]. This method has the benefit of being computationally inexpensive, allowing for temporally extensive analyses to be carried out, to the detriment of some physical accuracy.
Other models simplify the heat distribution as two well-mixed bodies of water at the top and bottom, separated by a thermocline of negligible width[@JackDew2018; @Booysen2017; @Nel2018].
While requiring more computer resources than the single-volume models, the two-volume models still a provide relatively computationally inexpensive means of analysing hot water usage, while capturing some additional physical characteristics such as the rapid ‘running out’ of hot water.
Finally, some hot water cylinder models use computational fluid dynamics (CFD) software to maintain very high amounts of physical accuracy, essentially allowing the determination of water temperature at any point within the cylinder[@Kong2016; @Yaici2013]. 
Within these models there must be the ability to simulate the demand of hot water.
The model in [@Heleno2015] simply schedules three 35L, 38° hot water events at three separate times through the day.
The model in [@JackDew2018] simulates domestic hot water usage by assuming up to three major use events (representing showers, bathing etc) that are random and normally distributed about fixed times of day, with additional minor usage events (representing hand washing etc) having equal probability of occurring between specified intervals at other times.
For much of the hot water cylinder research previously mentioned however, the methodology around demand simulation is not elucidated. 
Statistical insights gained from parameters within appropriate demand forecasting models have to potential to be incorporated into physical models to simulate demand in a manner that closely resembles reality. This would improve how accurately these physical models represent reality, in turn improving accuracy of results from smart control simulations.

## Contribution of this thesis to the literature

To the best of my knowledge, there is no existing literature that compares a range of models to forecast residential hot water electricity demand.
Within the existing literature, the piece of research most similar to that conducted for this thesis is that of Gelažanskas and Gamage[@Gelazanskas2015]. 
These researchers also compare a selection of forecasting methods to predict residential hot water demand.
These were fitted to volumetric hot water data from around 95 households in the UK. 
Their research also used the R programming language, and used simplistic models as benchmarks by which to compare others to. 
They explored a number of time series models for prediction, including exponential smoothing, ARIMA, seasonal decomposition of time series by Loess (STL)[^1], and combinations of these.
Predictions were made for 24 hours ahead, and models were compared against one another for accuracy.
Forecasts were also constructed for aggregated demand data, that is, the demand of all the households added together.
Accuracy of all models considered was greatly improved when aggregating data in this manner.
While my thesis draws on the key findings within [@Gelazanskas2015], it differs in a number of ways, which are shown in Table \@ref(tab:gelazanskasComparison).

[^1]: These methods are explained in more detail in Chapter \@ref(methodology).

```{r gelazanskasComparison}
df1 <- data.frame(Characteristics = c("Data resolution", "Data type", "Forecast length", "Forecast methods", "Comparative metrics"),
                  This_thesis = c("Half hour", "Electricity demand", "Half hour", "Time series, causal, AI", "Various"), 
                  Gelazanskas = c("1 hour", "Volumetric demand", "24 hours", "Time series", "Accuracy"))

library(kableExtra)
df1 %>% 
 knitr::kable(col.names = c(" ", "This thesis", "Gelažanskas and Gamage"),
              caption = "Comparison between this thesis and the most similar piece of existing literature", 
              format = "latex") %>%
  row_spec(0, bold = TRUE) %>% 
  kable_styling()
```


