# Conclusion {#conclusion}

Smart control of hot water cylinders has a role to play in a smooth and cost-effective transition to a low-carbon society.
To best realise this potential, we need the ability to make accurate demand forecasts at the level of individual cylinders.

This thesis set out to build and compare a selection of models to forecast residential hot water electricity demand using only data in the format currently available from smart meters in New Zealand. An underlying goal was to recommend an 'optimal' hot water electricity demand forecasting model for incorporation into a smart-control system. Optimal models for this purpose should provide accurate results at household level, and be reasonably fast to compute.
Models were also compared according to their suitability for incorporation in physical simulations. This consideration required model outputs to be interpretable, and provide outputs that were reasonably similar to the original data.

The results suggest the STL + ARIMAX model shows the most promise for incorporation within a smart control system. 
This model involves decomposition of the hot water demand data into seasonal, trend and remainder components, and modelling the remainder as an ARIMAX process with lagged values of other electricity demand as an external variable. 
This method provided a combination of accuracy, computational speed and interpretability that was unmatched in other methods considered. 
It was, however, outperformed by a number of other methods in physical fidelity. 
This was due to the output producing results that were not physically obtainable by the cylinder element, as well as having higher stochasticity than the data. 

## Potential for further work 

The research conducted for this thesis has provided groundwork for additional research relating to both smart control, and appliance level demand forecasting. This additional research may broadly be separated into two categories; 
(i) better quantifying the benefits of incorporating forecasting within smart control, and 
(ii) further refinements of the models, including adaptation and evaluation against different data formats.


### Quantifying the benefits of forecasting within smart control objectives

The smart control system proposed in Section \@ref(implimentation) has a number of benefits over New Zealand's existing ripple control system. 
These benefits include: 

* accuracy improvements of predicted interruptible load
* energy efficiency improvements
* reduced impacts on service
* additional capacity for control

The obvious next step for this work is to incorporate the recommended forecasting model into hot water cylinder smart control scenarios (either simulated or real world) and determine the additional benefits it can provide over control methods that do not incorporate demand forecasting.
As part of this process, work must be done in translating parameters of the forecasting models into demand simulation parameters, as part of the physical model mentioned in Fig. \@ref(fig:controlSystem).

New Zealand's current ripple control system suppresses an aggregate of elements equally, with no consideration to individualised use patterns.
In order to reduce impacts on service, the aggregate of elements can only be suppressed infrequently for short lengths of time, so that higher demand households do not run out of hot water.
The necessity of excluding households that may be negatively impacted by control means that all other households have more capacity for control than is currently undertaken.
While this is a reasonable assumption, the extent to which smart control with demand forecasting offers additional control capacity has not been quantified within this research.
Further work could be made to estimate the quantity of this additional capacity.
In addition, energy efficiency improvements gained by controlling according to the system presented in Fig. \@ref(fig:controlSystem) could be quantified.

### Additional model refining and testing

Some of the models presented in this thesis have the ability to be further refined to improve predictions.
The SVM model in particular provided inferior results during peak periods, which are the times when demand response is most valuable.
Peak period forecast accuracy of this model could potentially be improved by including additional parameters.

Another research angle would be to refine the models in this research to forecast higher resolution data.
The element within a typical hot water cylinder is controlled thermostatically by an "on-off" (otherwise known as "bang-bang") controller. This type of controller turns the element fully "on" when the water temperature drops below a certain temperature, and then fully off again once the water reaches another (slightly higher) temperature.
On small timescales, the element may then be considered a binary process, impacting our choice of forecasting model. 
Forecasting a binary output would involve the addition of a logistic function [@James2017] to existing models. Rather than producing a continuous output of the predicted element power as used in this thesis, models that incorporate a logistic function produce an output of the probability the element is on. This accommodates binary (on/off) predictions of element state.

An 'aggregate demand forecasting model' is mentioned in Fig. \@ref(fig:controlSystem). This refers to a forecast of aggregate demand for the households able to participate in demand response. 
Forecasting models developed in [@Gelazanskas2015] showed that when fitted to aggregated demand data, accuracy of predictions were higher than when fitted to individual household data.
It is unclear whether a sum of household level forecasts would outperform a forecast fitted to aggregated demand data using the recommended models in this thesis due to the use of other appliance electricity demand as an external regressor. 
The higher-performing models in this thesis could be fitted and tested using aggregated demand data to ascertain this.

To reduce computational time and model complexity, only half-hour and one-hour lags of other appliance demand were used as external regressors in models for all selected households.
It can be seen in Table \@ref(tab:ccvMaxLagTable) in the Appendix and the corresponding Fig. \@ref(fig:ccvMaxLagPlot) in Chapter \@ref(methodology) that some households have optimal cross-covariance lags that are greater than one hour. Household-specific lag values of external regressors could be incorporated into models as further work.

There is also potential for further exploration of the models considered in this work for forecasting the demand of other deferrable loads, such as electric vehicles.

## Closing remarks

This thesis compares models for forecasting individual household level hot water electricity demand, and proposes a particular smart control system that incorporates them.
Smart control of hot water cylinders has the potential to increase both the economic efficiency of an electricity grid, and the energy efficiency of domestic hot water use.
Both of these efficiency gains suppress the price of electricity, hastening the electrification of high-carbon industries such as transport and industrial processing.
Electricity demand forecasting provides a demonstrable improvement to smart control systems, and as such, is an important tool in the transition to a low-carbon society.


<!--
### Generalised additive models
_One article used this method. Was quite involved to describe and build, ran out of time. Not sure if worth mentioning_

Another prediction method that is used for electricity demand forecasting is _generalized additive models_. These...

### Exponential smoothing
_Again, one article used this method. Didn't get around to incorporating but this one should actually be quite easy to include if you consider it worthwhile._

Another forecasting model referred to within the literature is exponential smoothing. This method is generally regarded as performing similarly to ARIMA modelling, but can outperform ARIMA in forecasts of extremely stochastic data.


-->

<!--
Despite the reasonable forecasting accuracy of the vector autoregression method above, the model diverges from physical reality in two crucial ways. First, the model is fitted using ordinary least squares, with no regard for maintaining the forcasted demand to be greater than zero.

In addition, vector autoregression assumes continuity of the process. While the half-hour data (being actually 30 minute averages of 1 minute data) appears roughly continuous, the 1 minute data shows the element is essentially a discrete process, with the element either being fully on or fully off.
-->
