# Automate installation of dependent packages after upgrading base R
# There's probably a better way of doing this...
install.packages("R.utils")
devtools::install_github("CfSOtago/GREENGridData")
install.packages("vars")
install.packages("ggplot2")
install.packages("ggpmisc")
install.packages("remotes")
remotes::install_github("DavZim/varsExtra")
install.packages("varsExtra")
install.packages("dplyr")
install.packages("TSA")
install.packages("forecast")
install.packages("knitr")
install.packages("scales")
install.packages("TSA")
install.packages("dplyr")
install.packages("data.table")
install.packages("ggseas")